from __future__ import annotations

import json
import os
import tempfile
from datetime import UTC, datetime

from fastapi import APIRouter, Depends, File, HTTPException, Request, UploadFile
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from src.api.routes.auth import require_auth
from src.core.crypto import decrypt_cookies, encrypt_cookies
from src.core.download_engine import DownloadEngine
from src.db.models.cookie import Cookie
from src.db.session import get_db
from src.schemas.cookie import CookieListResponse, CookieResponse, CookieTestResponse

router = APIRouter()


def _validate_netscape_content(content: str) -> tuple[bool, str]:
    if not content.strip().startswith("# "):
        return False, "Missing Netscape header"
    required = ["sessionid", "tt_csrf_token"]
    lines = content.strip().split("\n")
    cookie_names = set()
    for line in lines:
        if line.startswith("#") or not line.strip():
            continue
        parts = line.split("\t")
        if len(parts) >= 7:
            cookie_names.add(parts[5].strip())
    missing = [c for c in required if c not in cookie_names]
    if "sessionid" in missing:
        return False, "Missing sessionid cookie. Make sure you are logged in to tiktok.com before exporting."
    return True, ""


def _validate_json_content(content: str) -> tuple[bool, str, list[dict]]:
    try:
        data = json.loads(content)
    except json.JSONDecodeError:
        return False, "Invalid JSON format.", []
    if not isinstance(data, list):
        return False, "JSON must be an array of cookie objects.", []
    found_names = {c.get("name", "") for c in data if isinstance(c, dict)}
    if "sessionid" not in found_names:
        return False, "Missing sessionid cookie. Make sure you are logged in to tiktok.com before exporting.", []
    if not all(isinstance(c, dict) for c in data):
        return False, "Each cookie must be a JSON object.", []
    for cookie in data:
        if "domain" not in cookie or "name" not in cookie or "value" not in cookie:
            return False, "Each cookie must have 'domain', 'name', and 'value' fields.", []
    return True, "", data


def json_cookies_to_netscape(cookies_list: list[dict]) -> str:
    lines = ["# Netscape HTTP Cookie File", "# Generated by TikDown"]
    for c in cookies_list:
        domain = c.get("domain", ".tiktok.com")
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expires = str(int(c.get("expirationDate", 4102444800)))
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append("\t".join([domain, flag, path, secure, expires, name, value]))
    return "\n".join(lines) + "\n"


def _test_cookies_with_ytdlp(cookiefile_path: str) -> tuple[bool, str]:
    try:
        engine = DownloadEngine(cookiefile_path=cookiefile_path)
        engine.extract_info("https://www.tiktok.com/@tiktok", download=False)
        return True, "Cookies are valid and working."
    except Exception as e:
        msg = str(e)
        if "Sign in" in msg or "login" in msg.lower():
            return False, "Cookies are expired or invalid (login required)."
        return False, f"Validation failed: {msg[:200]}"


@router.get("", response_model=CookieListResponse)
async def list_cookies(
    request: Request,
    db: AsyncSession = Depends(get_db),
):
    await require_auth(request)
    result = await db.execute(select(Cookie).order_by(Cookie.created_at.desc()))
    cookies = list(result.scalars().all())
    return CookieListResponse(cookies=cookies)


@router.post("", response_model=CookieResponse, status_code=201)
async def upload_cookie(
    request: Request,
    file: UploadFile = File(...),
    account_id: str | None = None,
    db: AsyncSession = Depends(get_db),
):
    await require_auth(request)

    raw = (await file.read()).decode("utf-8", errors="replace")
    original_format = "txt"
    netscape_content = ""

    if raw.strip().startswith("["):
        valid, msg, cookies_list = _validate_json_content(raw)
        if not valid:
            raise HTTPException(status_code=400, detail=msg)
        original_format = "json"
        netscape_content = json_cookies_to_netscape(cookies_list)
    elif raw.strip().startswith("# "):
        netscape_content = raw
    else:
        raise HTTPException(
            status_code=400,
            detail="Unrecognized cookie format. Export from 'Get cookies.txt LOCALLY' extension in TXT or JSON format.",
        )

    valid, msg = _validate_netscape_content(netscape_content)
    if not valid:
        raise HTTPException(status_code=400, detail=msg)

    name = file.filename or "cookies.txt"
    encrypted = encrypt_cookies(raw)

    temp_path = ""
    try:
        fd, temp_path = tempfile.mkstemp(suffix=".txt", prefix="tikdown_validate_")
        with os.fdopen(fd, "w") as f:
            f.write(netscape_content)

        is_valid, test_msg = _test_cookies_with_ytdlp(temp_path)
        status_val = "valid" if is_valid else "invalid"

        cookie = Cookie(
            name=name,
            account_id=account_id,
            original_format=original_format,
            encrypted_content=encrypted,
            status=status_val,
            last_validated_at=datetime.now(UTC),
        )
        db.add(cookie)
        await db.commit()
        await db.refresh(cookie)
        return cookie
    finally:
        if temp_path and os.path.exists(temp_path):
            os.unlink(temp_path)


@router.post("/{cookie_id}/test", response_model=CookieTestResponse)
async def test_cookie(
    request: Request,
    cookie_id: str,
    db: AsyncSession = Depends(get_db),
):
    await require_auth(request)
    cookie = await db.get(Cookie, cookie_id)
    if not cookie:
        raise HTTPException(status_code=404, detail="Cookie not found")

    raw = decrypt_cookies(cookie.encrypted_content)
    netscape_content = raw

    if raw.strip().startswith("["):
        cookies_list = json.loads(raw)
        netscape_content = json_cookies_to_netscape(cookies_list)

    temp_path = ""
    try:
        fd, temp_path = tempfile.mkstemp(suffix=".txt", prefix="tikdown_test_")
        with os.fdopen(fd, "w") as f:
            f.write(netscape_content)

        is_valid, test_msg = _test_cookies_with_ytdlp(temp_path)
        cookie.status = "valid" if is_valid else "invalid"
        cookie.last_validated_at = datetime.now(UTC)
        await db.commit()

        return CookieTestResponse(
            id=cookie.id,
            status=cookie.status,
            message=test_msg,
            validated_at=cookie.last_validated_at,
        )
    finally:
        if temp_path and os.path.exists(temp_path):
            os.unlink(temp_path)


@router.delete("/{cookie_id}", status_code=204)
async def delete_cookie(
    request: Request,
    cookie_id: str,
    db: AsyncSession = Depends(get_db),
):
    await require_auth(request)
    cookie = await db.get(Cookie, cookie_id)
    if not cookie:
        raise HTTPException(status_code=404, detail="Cookie not found")
    await db.delete(cookie)
    await db.commit()
