"""initial_schema

Revision ID: 96bcee3a8d12
Revises: 
Create Date: 2026-07-02 13:01:13.647077
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '96bcee3a8d12'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cookies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('original_format', sa.String(length=10), nullable=False),
    sa.Column('encrypted_content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitored_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tiktok_username', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_video_timestamp', sa.Integer(), nullable=True),
    sa.Column('options_json', sa.Text(), nullable=True),
    sa.Column('cookie_id', sa.String(length=36), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('total_likes', sa.Integer(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('profile_last_refreshed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitored_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitored_accounts_tiktok_username'), ['tiktok_username'], unique=True)

    op.create_table('settings',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('activity_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['monitored_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_events_event_type'), ['event_type'], unique=False)

    op.create_table('videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('monitored_account_id', sa.String(length=36), nullable=False),
    sa.Column('tiktok_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('upload_date', sa.String(length=20), nullable=True),
    sa.Column('upload_timestamp', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=512), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['monitored_account_id'], ['monitored_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_monitored_account_id'), ['monitored_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_tiktok_id'), ['tiktok_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_tiktok_id'))
        batch_op.drop_index(batch_op.f('ix_videos_monitored_account_id'))

    op.drop_table('videos')
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_events_event_type'))

    op.drop_table('activity_events')
    op.drop_table('settings')
    with op.batch_alter_table('monitored_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitored_accounts_tiktok_username'))

    op.drop_table('monitored_accounts')
    op.drop_table('cookies')
    # ### end Alembic commands ###
